### ISSUE TITLE
Stuck at Installing build\app\outputs\apk\app.apk...

### ISSUE THREAD

**Issue by wyxcoder** [fluttercommunity/flutter_downloader#170]
I used to use 1.2.1, it worked fine and nice. Since a few days ago, I got 'keep stopping'. Then I tried to use the most up to date version and need add a new MyApplication.

But with it, I cannot start the app, it stuck at Installing build\app\outputs\apk\app.apk..., any idea?

**Comment by johnny-stevie** [comment]
in android manifest.xml change 
`android:name=".DemoApplication"`
to 
`android:name="io.flutter.app.FlutterApplication"`
The problem is that the line above is the one that starts the application.
See if that will help, it helped me when I reached that problem.

**Comment by johnny-stevie** [comment]
Scrap that, I have found out that that you need to put the MyApplication file under your project dir like com.xxx.xxx. This makes it work as thats where build.gradle goes to to start your app.

**Comment by xiongjianchang** [comment]
My project also had this problem. I thought Android build functionality had failed, but I didn't know how to get it working again.

**Comment by johnny-stevie** [comment]
@xiongjianchang Did you figure it out?

**Comment by xiongjianchang** [comment]
@johnny-stevie @wyxcoder 
My problem has been solved.
1. Select 'File > Open... ',
2. Navigate to your Flutter app directory, select the 'android' folder inside, and click 'OK' to open an android project.
3. Select 'File > invalidate caches/restart... '.
Wait until the project is rebuilt and ready to use.

**Comment by RafaelR7** [comment]
I got the same problem, changing the `android:name` to `.DemoApplication` makes the build stuck,
changing the `android:name`  to the default value, when I try to make a download crashes de app without any error message.

**Comment by RafaelR7** [comment]
I was able to build the apk, in the DemoApplication.java insert at the beginning `package` of your project ie: `io.com.hellorword;`,

**Comment by johnny-stevie** [comment]
So you were missing a java import package statement? 
I realised for my project that I had to write my `DemoApplication` in kotlin instead of java which was the whole reason why it didn't work.
Good to know you've solved your issue.
Anybody else reading this with a problem similar to mine, remember, CHECK which language your android folder uses!!!

**Comment by RafaelR7** [comment]
@johnny-stevie Yes, I was missing the package import, I just realise that by looking into the example, the readme of the package is missing this import.

**Comment by HassanDev13** [comment]
<img width="459" alt="Github1" src="https://user-images.githubusercontent.com/48941486/72209895-bb9e7f00-34ab-11ea-93e0-3f01d7d602de.PNG">
help plaise?

**Comment by HassanDev13** [comment]
<img width="502" alt="Github2" src="https://user-images.githubusercontent.com/48941486/72209949-5303d200-34ac-11ea-9073-a6fb6c3340d9.PNG">
my app keep craching

**Comment by johnny-stevie** [comment]
Did you implement the implement registrar code for the FlutterDownloader
package?

**Comment by HassanDev13** [comment]
I put my Class like u said and i import it and i just copy paste from
documentation

**Comment by RafaelR7** [comment]
take a look at the example, and compare it with your project, because the example is working.
It might help, that's what I did.

**Comment by johnny-stevie** [comment]
For me the problem was that it had to be implemented in Kotlin instead of
Java. Check which language you have to setup the package in.

**Comment by sethchhim** [comment]
@HassanDev13 

I just fixed my crash by including package declaration above imports. If you just copy and paste the example it won't work because it is missing.

```
package com.github.sethchhim.example

import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugins.GeneratedPluginRegistrant
import vn.hunghd.flutterdownloader.FlutterDownloaderPlugin
```

Hope this helps.

**Comment by hnvn** [comment]
See https://github.com/fluttercommunity/flutter_downloader/issues/214#issuecomment-570776556

**Comment by HassanDev13** [comment]
![Github1](https://user-images.githubusercontent.com/48941486/72216865-132e0080-3527-11ea-971c-85b87902d0bb.PNG)
the problem still exists
I noticed the GeneratedPluginRegistrant class of Exemple is different with my project any idea?

**Comment by hnvn** [comment]
delete your `android` folder and run this command to re-generate it. 
```
flutter create -a java .
```

**Comment by HassanDev13** [comment]
i run this command and he show me : 
No option specified for the output directory.
Create a new Flutter project.
If run on a project that already exists, this will repair the project, recreating any files that are missing.

Usage: flutter create <output directory>
-h, --help                     Print this usage information.
    --[no-]pub                 Whether to run "flutter pub get" after the project has been created.
.
.
.
.
    --project-name             The project name for this new Flutter project. This must be a valid dart package name.
-i, --ios-language             [objc, swift (default)]
-a, --android-language         [java, kotlin (default)]
    --[no-]androidx            Generate a project using the AndroidX support libraries
                               (defaults to on)
Run "flutter help" to see global options.

**Comment by hnvn** [comment]
```
flutter create -a java .
```
There'a dot sign at the end the command, it's a part of the syntax, not a typo

**Comment by HassanDev13** [comment]
it work's no  crashing ...when i download image it's okey but pdf or video show me Failed
 
![github_mobile](https://user-images.githubusercontent.com/48941486/72222386-64a8b080-3564-11ea-9822-0bd41ae6f0ed.jpg)

**Comment by hnvn** [comment]
any logs?

**Comment by HassanDev13** [comment]
![logs](https://user-images.githubusercontent.com/48941486/72286143-d821ef00-3644-11ea-80fc-131ef624ed92.PNG)
when i click in the download icon for pdf fils

**Comment by hnvn** [comment]
I believe it related to this issue: https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted

**Comment by hnvn** [comment]
Anything updated? If not, I am going to close this issue.

**Comment by HassanDev13** [comment]
the problem still with me

**Comment by hnvn** [comment]
Give me logs from Logcat
