### ISSUE TITLE
Android: Build fails on 1.0+ at app:transformClassesWithMultidexlistForDebug

### ISSUE THREAD

**Issue by derTuca** [fluttercommunity/flutter_downloader#19]
The build fails when using the latest version of the plugin (with compile SDK 28), giving the following error:
```
Program type already present: com.google.common.util.concurrent.ListenableFuture
```

**Comment by derTuca** [comment]
Sure, it is as follows:

```
import com.google.gms.googleservices.GoogleServicesPlugin

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystorePropertiesFile = rootProject.file("key.properties")
def keystoreProperties = new Properties()
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId "<APPLICATION-ID>"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }

}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "com.android.support:support-v4:28.0.0"
    implementation "com.android.support:appcompat-v7:28.0.0"
    implementation "com.android.support:cardview-v7:28.0.0"
    implementation "com.android.support:customtabs:28.0.0"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
apply plugin: 'com.google.gms.google-services'
GoogleServicesPlugin.config.disableVersionCheck = true
```

**Comment by hnvn** [comment]
I've just published a new version that upgrades `compileSdkVersion` to 28. I try turning `multiDexEnabled` to `true` and example project works well. To be honest, I don't know what your issue comes from but I see your configuration of `gradle` contains some components from android support libraries, there's probably conflictions between them. You can try to upgrade to latest version of this plugin and let me know if the problem still occurs

**Comment by derTuca** [comment]
I updated to the latest version and the issue still persists. I have created a new project and started adding my plugins one by one, and the conflicts seems to be with `cloud_firestore` (luckily the first one I tested). Could the Firebase SDK have conflicting components?

**Comment by hnvn** [comment]
This issue is related to `WorkManager` dependency: https://issuetracker.google.com/issues/116154359

To work around it, place following code in your `build.gradle` file (in `android` folder, not `app` folder):
```gradle
configurations.all {
    exclude group: 'com.google.guava', module: 'listenablefuture'
}
```

**Comment by derTuca** [comment]
I still get the same error: 
```
com.android.build.api.transform.TransformException: Error while generating the main dex list.
```

I have tried the snipped you gave me and the one suggested in the answer, but none of them work. I have also tried excluding the module in the build.gradle of your plugin, but then the compilation would fail because it can't find the module (duh).

**Comment by hnvn** [comment]
I've just released a new version to deal with this issue. I've tested on the example project and it can be compiled with `firebase` libraries now. But to get it worked, you have to add some additional configuration in `gradle` file, add following codes in file `build.gradle` inside `android` folder:

```
configurations.all {
    exclude group: 'com.google.guava', module: 'failureaccess'

    resolutionStrategy {
         eachDependency { details ->
             if('guava' == details.requested.name) {
                 details.useVersion '27.0-android'
             }
          }
     }
}
```

**Comment by hnvn** [comment]
@derTuca , Have you worked around this issue yet?
