### ISSUE TITLE
Downloading stuck in progress

### ISSUE THREAD

**Issue by AAverin** [fluttercommunity/flutter_downloader#340]
Got this once so far so can't provide any more details.
Notification was stuck at `in progress` and killing the app or going offline didn't remove it. In logs progress was 100% and no visible errors.
I was downloading 2 files in parallel, the other one finished just fine.

**Comment by AAverin** [comment]
Downloading many files in the queue, notifications can often get stuck in Progress due to some kind of error and there is no way to dismiss them. There should be at least a way to make progress notifications dismissable

**Comment by ahmadkhedr** [comment]
Same issue here

**Comment by canitez** [comment]
I have the same problem when I download batch files, some files remain in progress. Well, did you find a solution to this?

**Comment by canitez** [comment]
I have the same problem when I download batch files, some files remain in progress. Well, did you find a solution to this?

**Comment by AAverin** [comment]
Not really. My only theory so far is that if there is an error, download can get stuck.
But probably it's a bug somewhere inside the plugin itself.
Can anyone confirm if there is an issue on iOS too? I have only seen in on Android so far.

**Comment by AAverin** [comment]
@hnvn could you please take a look at this issue? Looks to be quite critical.
Is there anything we can do?

**Comment by hnvn** [comment]
It's very appreciated if you can give me some error logs or a way to reproduce this issue

**Comment by AAverin** [comment]
@hnvn I didn't see any errors in the logs.
What I have is a default setting of 2 parallel downloads and have tried to schedule multiple downloads at the same time. Some of them get stuck.
I will be testing this more in the coming days, but I see there are also
https://github.com/fluttercommunity/flutter_downloader/issues/353
and
https://github.com/fluttercommunity/flutter_downloader/issues/345
which basically talk about the same problem.

**Comment by AAverin** [comment]
@hnvn If you have any extra logging I can enable, I could run a custom branch of the library against my code to find what the problem is.

**Comment by canitez** [comment]
I examine the logs but I don't see any problems. What kind of logo do you need? It's okay when I try to download one by one. However, when we use it in a loop, it gives this error. Some downloads have a status of 2. I'm trying to restart them but the notification screen hangs. It doesn't fix without restarting the phone.

**Comment by canitez** [comment]
W/WM-WorkSpec( 3063): Backoff delay duration less than minimum value
D/DownloadWorker( 3063): DownloadWorker{***,filename=66358,savedDir=/storage/emulated/0/Android/data/c***/files,header=,isResume=false
W/_photo_downloa( 3063): JNI critical lock held for 16.302ms on Thread[41,tid=3317,Runnable,Thread*=0xd8ce3800,peer=0x13040488,"pool-1-thread-7"]
I/flutter ( 3063): Background Isolate Callback: task (7b93dc9f-c8c8-48d8-b66c-625de3b924ed) is in status (DownloadTaskStatus(2)) and process (0)
I/flutter ( 3063): UI Isolate Callback: [7b93dc9f-c8c8-48d8-b66c-625de3b924ed, DownloadTaskStatus(2), 0]
D/DownloadWorker( 3063): Open connection to ***
D/DownloadWorker( 3063): Content-Type = image/jpeg
D/DownloadWorker( 3063): Content-Length = 165475
D/DownloadWorker( 3063): Charset = null
D/DownloadWorker( 3063): fileName = 66358
I/flutter ( 3063): Background Isolate Callback: task (7b93dc9f-c8c8-48d8-b66c-625de3b924ed) is in status (DownloadTaskStatus(2)) and process (2)
I/flutter ( 3063): UI Isolate Callback: [7b93dc9f-c8c8-48d8-b66c-625de3b924ed, DownloadTaskStatus(2), 2]
I/flutter ( 3063): Background Isolate Callback: task (7b93dc9f-c8c8-48d8-b66c-625de3b924ed) is in status (DownloadTaskStatus(2)) and process (14)
I/flutter ( 3063): UI Isolate Callback: [7b93dc9f-c8c8-48d8-b66c-625de3b924ed, DownloadTaskStatus(2), 14]
I/flutter ( 3063): Background Isolate Callback: task (7b93dc9f-c8c8-48d8-b66c-625de3b924ed) is in status (DownloadTaskStatus(2)) and process (26)
I/flutter ( 3063): UI Isolate Callback: [7b93dc9f-c8c8-48d8-b66c-625de3b924ed, DownloadTaskStatus(2), 26]
I/flutter ( 3063): Background Isolate Callback: task (7b93dc9f-c8c8-48d8-b66c-625de3b924ed) is in status (DownloadTaskStatus(2)) and process (38)
I/flutter ( 3063): UI Isolate Callback: [7b93dc9f-c8c8-48d8-b66c-625de3b924ed, DownloadTaskStatus(2), 38]
I/flutter ( 3063): Background Isolate Callback: task (7b93dc9f-c8c8-48d8-b66c-625de3b924ed) is in status (DownloadTaskStatus(2)) and process (49)
I/flutter ( 3063): UI Isolate Callback: [7b93dc9f-c8c8-48d8-b66c-625de3b924ed, DownloadTaskStatus(2), 49]
I/flutter ( 3063): Background Isolate Callback: task (7b93dc9f-c8c8-48d8-b66c-625de3b924ed) is in status (DownloadTaskStatus(2)) and process (61)
I/flutter ( 3063): UI Isolate Callback: [7b93dc9f-c8c8-48d8-b66c-625de3b924ed, DownloadTaskStatus(2), 61]
I/flutter ( 3063): Background Isolate Callback: task (7b93dc9f-c8c8-48d8-b66c-625de3b924ed) is in status (DownloadTaskStatus(2)) and process (73)
I/flutter ( 3063): UI Isolate Callback: [7b93dc9f-c8c8-48d8-b66c-625de3b924ed, DownloadTaskStatus(2), 73]
I/flutter ( 3063): Background Isolate Callback: task (7b93dc9f-c8c8-48d8-b66c-625de3b924ed) is in status (DownloadTaskStatus(2)) and process (84)
I/flutter ( 3063): UI Isolate Callback: [7b93dc9f-c8c8-48d8-b66c-625de3b924ed, DownloadTaskStatus(2), 84]
I/flutter ( 3063): Background Isolate Callback: task (7b93dc9f-c8c8-48d8-b66c-625de3b924ed) is in status (DownloadTaskStatus(2)) and process (96)
I/flutter ( 3063): UI Isolate Callback: [7b93dc9f-c8c8-48d8-b66c-625de3b924ed, DownloadTaskStatus(2), 96]
I/flutter ( 3063): Background Isolate Callback: task (7b93dc9f-c8c8-48d8-b66c-625de3b924ed) is in status (DownloadTaskStatus(2)) and process (100)
I/flutter ( 3063): UI Isolate Callback: [7b93dc9f-c8c8-48d8-b66c-625de3b924ed, DownloadTaskStatus(2), 100]
D/DownloadWorker( 3063): insert _data=/storage/emulated/0/Android/data/***/files/66358 date_added=1602756338803 datetaken=1602756338805 _display_name=66358 mime_type=image/jpeg description= title=66358 to MediaStore
I/flutter ( 3063): Background Isolate Callback: task (7b93dc9f-c8c8-48d8-b66c-625de3b924ed) is in status (DownloadTaskStatus(3)) and process (100)
I/flutter ( 3063): UI Isolate Callback: [7b93dc9f-c8c8-48d8-b66c-625de3b924ed, DownloadTaskStatus(3), 100]
D/DownloadWorker( 3063): File downloaded
I/WM-WorkerWrapper( 3063): Worker result SUCCESS for Work [ id=7b93dc9f-c8c8-48d8-b66c-625de3b924ed, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]

**Comment by AAverin** [comment]
@hnvn Can I help in any way solve this issue?
I can't release the app with notifications being stuck until user reboots the device

**Comment by hnvn** [comment]
I have no idea about your case until I can reproduce it

**Comment by AAverin** [comment]
@hnvn multiple people have already provided the steps
Just try downloading multiple files in queue. For me at least 1 notification in 6 gets stuck all the time. File seems to get downloaded correctly, but notification is stuck "in progress".

**Comment by hnvn** [comment]
Give a some codes that I can use to reproduce it. That's better and faster way I can help you out.

**Comment by canitez** [comment]
All you have to do is use the download code in a loop. You will surely get this error at the end of 5-6 cycles.

**Comment by AAverin** [comment]
@hnvn I have just run sample app and triggered download of 6 elements one after the other. 

Notice that jpg on the top stuck 

![Screenshot_20201023-083356](https://user-images.githubusercontent.com/1481332/96964352-99da2a00-150a-11eb-921d-ab3056ca14a2.jpg)

**Comment by AAverin** [comment]
![Screenshot_20201023-083750](https://user-images.githubusercontent.com/1481332/96964615-1240eb00-150b-11eb-8e7f-09e183231b63.jpg)
![Screenshot_20201023-083758](https://user-images.githubusercontent.com/1481332/96964626-153bdb80-150b-11eb-98ea-2d2a8dc533ad.jpg)

**Comment by AAverin** [comment]
@hnvn you can see that in the app, downloads are marked as ready, so they have probably finished successfully and are fine.
Problem are notifications that are now stuck "in progress" and can not be dismissed or removed until app is uninstalled

**Comment by hnvn** [comment]
This is fixed in v1.5.2

**Comment by ChemistryX** [comment]
@hnvn Thanks for the fix!

**Comment by hnvn** [comment]
With no more update, I believe this error has been fixed in v1.5.2.

**Comment by YaarPatandarAA** [comment]
This is not fixed, I am using the latest code from this repo. Downloading multiple files in a loop still caused one or some files notification to stay stuck.

I am on Android 11.

**Comment by imagination24** [comment]
> 

the same,version:1.8.1

**Comment by kader93t** [comment]
@imagination24 
i send a pull request if you want a solution you can see the pull request #697 and do it yourself until the problem fixed officially

**Comment by osamasaeed** [comment]
> > 
> 
> the same,version:1.8.1

same issue also in version 1.8.1
